// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinhKienDienTu_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409013347_AddGhiChuAndLyDoHuyToOrder")]
    partial class AddGhiChuAndLyDoHuyToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Cart", b =>
                {
                    b.Property<int>("Cart_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cart_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Cart_ID");

                    b.HasIndex("Product_ID");

                    b.HasIndex("User_ID", "Product_ID")
                        .IsUnique();

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Category", b =>
                {
                    b.Property<int>("Category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_ID"));

                    b.Property<string>("Ten_Danh_Muc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Category_ID");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Order", b =>
                {
                    b.Property<int>("Order_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_ID"));

                    b.Property<string>("Dia_Chi_Giao_Hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ly_Do_Huy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay_Dat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tong_Tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Trang_Thai_Thanh_Toan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Order_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetail_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetail_ID"));

                    b.Property<decimal>("Gia_Ban")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Order_ID")
                        .HasColumnType("int");

                    b.Property<int>("Order_ID1")
                        .HasColumnType("int");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int>("Product_ID1")
                        .HasColumnType("int");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.HasKey("OrderDetail_ID");

                    b.HasIndex("Order_ID1");

                    b.HasIndex("Product_ID1");

                    b.ToTable("Order_Detail", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Product", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_ID"));

                    b.Property<decimal>("Gia_Goc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Hinh_Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Phan_Tram_Giam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Promotion_ID")
                        .HasColumnType("int");

                    b.Property<int>("So_Luong_Ton")
                        .HasColumnType("int");

                    b.Property<int>("SubCategory_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ten_San_Pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trang_Thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Product_ID");

                    b.HasIndex("Promotion_ID");

                    b.HasIndex("SubCategory_ID");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Promotion", b =>
                {
                    b.Property<int>("Promotion_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Promotion_ID"));

                    b.Property<DateTime>("Ngay_Bat_Dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay_Ket_Thuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Phan_Tram_Giam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ten_Khuyen_Mai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Promotion_ID");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategory_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategory_ID"));

                    b.Property<int>("Category_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ten_Danh_Muc_Con")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategory_ID");

                    b.HasIndex("Category_ID");

                    b.ToTable("Sub_Category", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho_Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mat_Khau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("So_Dien_Thoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Cart", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienDienTu_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Order", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.OrderDetail", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Order_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienDienTu_Web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Product", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("Promotion_ID");

                    b.HasOne("LinhKienDienTu_Web.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategory_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.SubCategory", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("Category_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
