// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinhKienDienTu_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409083145_ExpandEncryptedColumns")]
    partial class ExpandEncryptedColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Cart", b =>
                {
                    b.Property<int>("Cart_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cart_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Cart_ID");

                    b.HasIndex("Product_ID");

                    b.HasIndex("User_ID", "Product_ID")
                        .IsUnique();

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Category", b =>
                {
                    b.Property<int>("Category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_ID"));

                    b.Property<string>("Ten_Danh_Muc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Category_ID");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId");

                    b.ToTable("ChatMessage", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.ChatSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestOrUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SessionId");

                    b.ToTable("ChatSession", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.GiftRule", b =>
                {
                    b.Property<int>("GiftRule_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiftRule_ID"));

                    b.Property<int>("GiftProduct_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MainProduct_ID")
                        .HasColumnType("int");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.HasKey("GiftRule_ID");

                    b.HasIndex("GiftProduct_ID");

                    b.HasIndex("MainProduct_ID");

                    b.ToTable("Gift_Rule", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.NewsletterSubscriber", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay_Dang_Ky")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Newsletter_Subscriber", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Order", b =>
                {
                    b.Property<int>("Order_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_ID"));

                    b.Property<string>("Dia_Chi_Giao_Hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ly_Do_Huy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay_Dat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Phi_Ship")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phuong_Thuc_Thanh_Toan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tien_Tiet_Kiem_Khuyen_Mai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tien_Tiet_Kiem_Voucher")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tong_Tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Trang_Thai_Don_Hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trang_Thai_Thanh_Toan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Voucher_ID")
                        .HasColumnType("int");

                    b.HasKey("Order_ID");

                    b.HasIndex("User_ID");

                    b.HasIndex("Voucher_ID");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetail_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Order_Detail_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetail_ID"));

                    b.Property<decimal>("Gia_Ban")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Don_Gia");

                    b.Property<int>("Order_ID")
                        .HasColumnType("int")
                        .HasColumnName("Order_ID");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int")
                        .HasColumnName("Product_ID");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int")
                        .HasColumnName("So_Luong");

                    b.Property<decimal?>("Thanh_Tien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Thanh_Tien");

                    b.HasKey("OrderDetail_ID");

                    b.HasIndex("Order_ID");

                    b.HasIndex("Product_ID");

                    b.ToTable("Order_Detail", null, t =>
                        {
                            t.HasTrigger("Calculate_Thanh_Tien");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Product", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_ID"));

                    b.Property<decimal>("Gia_Goc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Hinh_Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTphcmOnly")
                        .HasColumnType("bit");

                    b.Property<decimal>("Phan_Tram_Giam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Promotion_ID")
                        .HasColumnType("int");

                    b.Property<int>("So_Luong_Ton")
                        .HasColumnType("int");

                    b.Property<int>("SubCategory_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ten_San_Pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trang_Thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Product_ID");

                    b.HasIndex("Promotion_ID");

                    b.HasIndex("SubCategory_ID");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Promotion", b =>
                {
                    b.Property<int>("Promotion_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Promotion_ID"));

                    b.Property<DateTime>("Ngay_Bat_Dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay_Ket_Thuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Phan_Tram_Giam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ten_Khuyen_Mai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Promotion_ID");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Review", b =>
                {
                    b.Property<int>("Review_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Review_ID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Review_ID");

                    b.HasIndex("Product_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.SearchHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("User_ID");

                    b.ToTable("SearchHistory", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategory_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategory_ID"));

                    b.Property<int>("Category_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ten_Danh_Muc_Con")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategory_ID");

                    b.HasIndex("Category_ID");

                    b.ToTable("Sub_Category", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho_Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Mat_Khau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("So_Dien_Thoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Voucher", b =>
                {
                    b.Property<int>("Voucher_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Voucher_ID"));

                    b.Property<decimal>("Don_Toi_Thieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gia_Tri_Giam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Loai_Giam_Gia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ma_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Ngay_Bat_Dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay_Het_Han")
                        .HasColumnType("datetime2");

                    b.Property<int>("So_Luong_Da_Dung")
                        .HasColumnType("int");

                    b.Property<int>("So_Luong_Gioi_Han")
                        .HasColumnType("int");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Voucher_ID");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Wishlist", b =>
                {
                    b.Property<int>("Wishlist_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Wishlist_ID"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Wishlist_ID");

                    b.HasIndex("Product_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Wishlist", (string)null);
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Cart", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienDienTu_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.ChatMessage", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.GiftRule", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Product", "GiftProduct")
                        .WithMany()
                        .HasForeignKey("GiftProduct_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinhKienDienTu_Web.Models.Product", "MainProduct")
                        .WithMany()
                        .HasForeignKey("MainProduct_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiftProduct");

                    b.Navigation("MainProduct");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Order", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinhKienDienTu_Web.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("Voucher_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.OrderDetail", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Order_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienDienTu_Web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Product", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("Promotion_ID");

                    b.HasOne("LinhKienDienTu_Web.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategory_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Review", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienDienTu_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.SearchHistory", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.SubCategory", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("Category_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Wishlist", b =>
                {
                    b.HasOne("LinhKienDienTu_Web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinhKienDienTu_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LinhKienDienTu_Web.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
